# frozen_string_literal: true

source 'https://rubygems.org'

gem 'rails', '6.0.2.1'

gem 'bootstrap-sass'
gem 'jquery-rails'
gem 'rspec-rails'
gem 'sass-rails', '~> 5.0.0'
gem 'slim'
gem 'sqlite3'
gem 'will_paginate'
gem 'will_paginate-bootstrap'
