require: rubocop-rspec

AllCops:
  Exclude:
    - example/db/**/*
    - example/config/**/*
    - search_object.gemspec

# Disables "Line is too long"
LineLength:
  Enabled: false

# Disables Module has too many lines
ModuleLength:
  Enabled: false

# Disables "Missing top-level class documentation comment"
Documentation:
  Enabled: false

# Disables "Use each_with_object instead of inject"
Style/EachWithObject:
  Enabled: false

# Disables "Prefer reduce over inject."
Style/CollectionMethods:
  Enabled: false

# Disables "Block has too many lines."
Metrics/BlockLength:
  Enabled: false

# Disables "Example has too many lines."
RSpec/ExampleLength:
  Enabled: false

# Disables "Too many expectations."
RSpec/MultipleExpectations:
  Enabled: false
